name: CI Build

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  manual_pip_list:
    name: Thorough code check / python-3.8 / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install scikit-bio
      - name: Show pip list
        run: |
          pip list

  setup_based_dependencies:
    name: Basic code checks / python-${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9']
        exclude:
          # already tested in first_check job
          - python-version: 3.8
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip setup.py install
      - name: Show pip list
        run: |
          pip list
